
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqchxlpigndrmjbtyvhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxY2h4bHBpZ25kcm1qYnR5dmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzgwMTksImV4cCI6MjA2NDExNDAxOX0.Hniwe87ef6V22Y-g4N7AxsOSn4Ea5TUuDFujVfaIMuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if we have valid configuration
const hasValidConfig = SUPABASE_URL && 
                       SUPABASE_PUBLISHABLE_KEY && 
                       SUPABASE_URL.includes('supabase.co') &&
                       SUPABASE_PUBLISHABLE_KEY.length > 50;

// Create a null client for fallback
const nullClient = {
  auth: {
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    signInWithOAuth: () => Promise.resolve({ data: null, error: new Error('Supabase not configured') }),
    signOut: () => Promise.resolve({ error: null })
  },
  from: () => ({
    select: () => ({ eq: () => Promise.resolve({ data: null, error: new Error('Supabase not configured') }) }),
    insert: () => Promise.resolve({ error: new Error('Supabase not configured') }),
    update: () => ({ eq: () => Promise.resolve({ error: new Error('Supabase not configured') }) }),
    delete: () => ({ eq: () => Promise.resolve({ error: new Error('Supabase not configured') }) })
  }),
  functions: {
    invoke: () => Promise.resolve({ data: null, error: new Error('Supabase not configured') })
  }
} as any;

// Safe client creation with try-catch
let supabaseClient: any;
if (hasValidConfig) {
  try {
    supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } catch (error) {
    console.warn('Failed to create Supabase client:', error);
    supabaseClient = nullClient;
  }
} else {
  console.warn('Supabase configuration invalid:', { 
    hasUrl: !!SUPABASE_URL, 
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
    urlValid: SUPABASE_URL?.includes('supabase.co'),
    keyLength: SUPABASE_PUBLISHABLE_KEY?.length 
  });
  supabaseClient = nullClient;
}

export const supabase = supabaseClient;
export const isSupabaseConfigured = hasValidConfig;
