

name: Deploy to Supabase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Verify Supabase project
      run: |
        supabase --version
        echo "Project ID: yqchxlpigndrmjbtyvhu"
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Link Supabase project
      run: supabase link --project-ref yqchxlpigndrmjbtyvhu
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Run database migrations
      run: supabase db push
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Deploy Supabase functions
      run: supabase functions deploy
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Compile MDX content
      run: |
        npm run build:mdx
        echo "MDX compilation completed"
        ls -la src/compiled-content/

    - name: Build project
      run: npm run build
      env:
        VITE_SUPABASE_URL: https://yqchxlpigndrmjbtyvhu.supabase.co
        VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxY2h4bHBpZ25kcm1qYnR5dmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzgwMTksImV4cCI6MjA2NDExNDAxOX0.Hniwe87ef6V22Y-g4N7AxsOSn4Ea5TUuDFujVfaIMuc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

