
name: Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Run tests (if any)
      run: npm test --if-present
      
    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # For example, if using Netlify CLI:
        # npx netlify deploy --prod --dir=dist
        
    - name: Deploy preview
      if: github.event_name == 'pull_request'
      run: |
        echo "Deploying preview..."
        # Add your preview deployment commands here
        # For example, if using Netlify CLI:
        # npx netlify deploy --dir=dist
